---
sudo: required
language: python

services:
  - docker

install:
  - pip install ansible
  - pip install molecule
  - pip install docker-py
  - pip install docker

script:
  - docker version
  - molecule --version
  - ansible --version
  - molecule --debug test
