---
language: python
python:
  - "2.7"
  - "3.7"
services:
  - docker
install:
  - pip install molecule docker docker-py
script:
  - docker version
  - molecule --version
  - ansible --version
  - molecule test
