---
sudo: required
language: python

services:
  - docker

install:
  - pip install molecule docker docker-py

script:
  - docker version
  - molecule --version
  - ansible --version
  - molecule test
