---
sudo: required
language: python

services:
  - docker

install:
  - pip install ansible
  - pip install molecule
  - pip install docker-py

script:
  - docker version
  - molecule --version
  - ansible --version
  - molecule --debug test
