---
namespace: dynatrace
name: oneagent
version: 1.2.0
readme: README.md
authors:
  - Dynatrace LLC
description: Module to install and configure Dynatrace OneAgent deployment
license:
  - MIT
tags:
  - dynatrace
  - oneagent
  - monitoring
  - deployment
repository: https://github.com/Dynatrace/Dynatrace-OneAgent-Ansible
documentation: https://docs.dynatrace.com/docs/setup-and-configuration/dynatrace-oneagent/deployment-orchestration/ansible
build_ignore:
  - roles/oneagent/tests
  - roles/oneagent/examples