---
- name: >
    Basic OneAgent installation using a local installer. Hosts placed in unix hosts groups have its local installer paths defined in inventory file.
    Main node communicates with Windows hosts over SSH.
  hosts: windows,unix
  tasks:
    - name: Import Dynatrace OneAgent role
      ansible.builtin.import_role:
        name: dynatrace.oneagent.oneagent
