# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Set up build environment"
description: "Sets up build environment"

inputs:
  ansible-community-package-version:
    description: "The Ansible community package version to install"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: "Upgrade pip"
      shell: bash
      run: |
        pip install --upgrade pip
    - name: "Install dependencies"
      shell: bash
      run: |
        pip install "ansible==${{ inputs.ansible-community-package-version }}.*" ansible-lint
