---
- name: Check if OneAgent is installed
  stat:
    path: "{{ oneagent_ctl_bin_path }}"
  register: _oneagent_ctl_state

- name: Uninstall OneAgent
  command: "{{ oneagent_uninstall_cmd }}"
  args:
    removes: "{{ oneagent_ctl_bin_path }}"
  register: _oneagent_uninstall_result
  no_log: true
  ignore_errors: true
  when: _oneagent_ctl_state.stat.exists

- name: Verify uninstall result
  fail:
    msg: "{{ oneagent_uninstall_failed_unix | format(_oneagent_uninstall_result.rc,
      _oneagent_uninstall_result.stdout, _oneagent_uninstall_result.stderr) }}"
  when: _oneagent_ctl_state.stat.exists and
    _oneagent_uninstall_result.failed|default(false)
