---
- name: Check installers info
  include_tasks: install/install-check.yml

- name: Combine installation parameters
  set_fact:
    _oneagent_all_install_args: "{{ (oneagent_passed_install_args +
      oneagent_additional_reporting_params) | map('regex_replace', '(.*)', '\"\\1\"') | list }}"
  no_log: true

- name: Install OneAgent
  include_tasks: install/install-{{ oneagent_system_family }}.yml

- name: Post-installation steps
  include_tasks: install/post-install-{{ oneagent_system_family }}.yml
