---
- name: Reboot the host
  ansible.builtin.reboot:
    reboot_timeout: oneagent_reboot_timeout
  register: _oneagent_reboot_status
  when: oneagent_reboot_host | bool

- name: Check the host reboot status
  ansible.builtin.fail:
    msg: "{{ oneagent_reboot_failed }}"
  when: oneagent_reboot_host | bool and not _oneagent_reboot_status.rebooted|default(false)
