---
- name: Check if OneAgent is installed
  ansible.windows.win_stat:
    path: "{{ oneagent_ctl_bin_path }}"
  register: _oneagent_ctl_state

- name: Determine version of installed OneAgent
  ansible.windows.win_command: '"{{ oneagent_ctl_bin_path }}" --version'
  register: _oneagent_installed_agent_version
  when: _oneagent_ctl_state.stat.exists
  changed_when: false
