---
- name: >
    Download OneAgent installer in specific version to a custom directory with additional OneAgent install parameters.
    Both linux_other and linux_arm have different user specified by platform args parameter.
  hosts: linux_other,linux_arm
  # credentials.yml file contains oneagent_environment_url and
  # oneagent_paas_token variables that needs to be stored securely
  vars_files:
    - credentials.yml
  vars:
    oneagent_download_dir: /home/user1
    oneagent_version: 1.199.247.20200714-111723
    oneagent_install_args:
      - INSTALL_PATH=/opt/example
      - GROUP=example_group
      - --set-host-name=new_host_name
      - --set-host-tag=new_tag
      - --set-host-property=property1
      - --set-host-property=other=property
  tasks:
    - name: Import Dynatrace OneAgent role
      ansible.builtin.import_role:
        name: dynatrace.oneagent.oneagent
