---
- name: Remove leftover signature
  ansible.builtin.file:
    path: "{{ oneagent_ca_cert_dest_path }}"
    state: absent

- name: Remove leftover installer
  ansible.builtin.file:
    path: "{{ oneagent_installer_path }}"
    state: absent
  changed_when: false
