---
- name: Remove installer scratch directory
  ansible.builtin.file:
    path: "{{ _oneagent_installer_scratch.path }}"
    state: absent
  when: _oneagent_installer_scratch.path is defined
  changed_when: false
