---
molecule:
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: milcom/centos7-systemd
    privileged: true
    exposed_ports:
      - 9999/tcp
    published_ports:
      - 0.0.0.0:9999:9999/tcp
provisioner:
  name: ansible
  options:
    vvv: true
    skip-tags: uninstall
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    # - lint
    # - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    # - destroy
verifier:
  name: testinfra
  options:
    v: 1
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
