Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "debian/jessie64"
  c.vm.hostname = "default-debian-jessie64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-dt-sible-default-debian-jessie64"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
