---
- name: Validate installation directory name doesn't contains spaces
  ansible.builtin.fail:
    msg: "{{ oneagent_install_dir_contains_spaces }}"
  when: "' ' in oneagent_install_path"

- name: Validate download directory name doesn't contain spaces
  ansible.builtin.fail:
    msg: "{{ oneagent_download_dir_contains_spaces }}"
  when: "oneagent_is_operation_installation and ' ' in oneagent_download_path"

- name: Validate if download directory is available
  ansible.builtin.stat:
    path: "{{ oneagent_download_path }}"
  register: _oneagent_download_path_state
