---
vagrant:
  raw_config_args:
    - "ssh.insert_key = false"
    - "vm.network 'forwarded_port', guest: 80, host: 9999"

dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: instance
    box: centos/7

provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: devtesting
  test_sequence:
    # - lint
    - destroy
    - dependency
    - create
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  options:
    v: 1
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  lint:
    name: flake8
