import tempfile
from enum import Enum
from pathlib import Path

COLLECTION_NAMESPACE = "dynatrace"
COLLECTION_NAME = "oneagent"
ROLE_NAME = "oneagent"

ANSIBLE_USER_KEY = "ansible_user"
ANSIBLE_PASS_KEY = "ansible_password"
ANSIBLE_CONNECTION_KEY = "ansible_connection"

HOSTS_TEMPLATE_FILE_NAME = "hosts.yml"
CREDENTIALS_FILE_NAME = "credentials.yml"
PLAYBOOK_TEMPLATE_FILE_NAME = "oneagent.yml"

INSTALLED_COLLECTIONS_DIR_PATH = Path.home() / ".ansible" / "collections"
COLLECTION_NAMESPACE_DIR_PATH = INSTALLED_COLLECTIONS_DIR_PATH / "ansible_collections" / COLLECTION_NAMESPACE
ROLE_DIR_PATH = COLLECTION_NAMESPACE_DIR_PATH / COLLECTION_NAME / "roles" / ROLE_NAME
TESTS_DIR_PATH = ROLE_DIR_PATH / "tests"

FAILED_DEPLOYMENT_EXIT_CODE = 2
SUCCESSFUL_DEPLOYMENT_EXIT_CODE = 0
VARIABLE_PREFIX = f"{COLLECTION_NAME}_"

RESOURCES_DIR_PATH = TESTS_DIR_PATH / "resources"
ANSIBLE_RESOURCES_DIR_PATH = RESOURCES_DIR_PATH / "ansible"
INSTALLERS_DIR_PATH = RESOURCES_DIR_PATH / "installers"

INSTALLER_CERTIFICATE_FILE_NAME = "dt-root.cert.pem"
INSTALLER_PRIVATE_KEY_FILE_NAME = "dt-root.key"
SERVER_CERTIFICATE_FILE_NAME = "server.pem"
SERVER_PRIVATE_KEY_FILE_NAME = "server.key"

INSTALLER_PARTIAL_NAME = "Dynatrace-OneAgent"
INSTALLER_SYSTEM_NAME_TYPE_MAP = {"linux": "linux", "unix": "linux", "aix": "aix", "windows": "windows"}

INSTALLER_SERVER_TOKEN = "abcdefghijk1234567890"


class InstallerVersion(Enum):
    OLD = "1.199.0.20241008-150308"
    LATEST = "1.300.0.20241008-150308"


UNIX_DOWNLOAD_DIR_PATH = Path("/tmp")
UNIX_INSTALL_DIR_PATH = Path("/opt") / "dynatrace" / "oneagent"
UNIX_ONEAGENTCTL_BIN_NAME = "oneagentctl"
UNIX_ONEAGENTCTL_PATH = UNIX_INSTALL_DIR_PATH / "agent" / "tools" / UNIX_ONEAGENTCTL_BIN_NAME

WINDOWS_DOWNLOAD_DIR_PATH = Path("%TEMP%")
WINDOWS_INSTALL_DIR_PATH = Path("C:\\Program Files") / "dynatrace" / "oneagent"
WINDOWS_ONEAGENTCTL_BIN_NAME = "oneagentctl.exe"
WINDOWS_ONEAGENTCTL_PATH = WINDOWS_INSTALL_DIR_PATH / "agent" / "tools" / WINDOWS_ONEAGENTCTL_BIN_NAME

TEST_RUN_DIR_PATH = Path(tempfile.gettempdir()) / "ansible_oneagent_tests_run_dir"
WORK_INSTALLERS_DIR_PATH = TEST_RUN_DIR_PATH / "installers"
WORK_LOGS_DIR_PATH = TEST_RUN_DIR_PATH / "logs"
WORK_SERVER_DIR_PATH = TEST_RUN_DIR_PATH / "server"
WORK_DIR_PATH = TEST_RUN_DIR_PATH / "work_dir"

TEST_PLAYBOOK_FILE = WORK_DIR_PATH / PLAYBOOK_TEMPLATE_FILE_NAME
TEST_INVENTORY_FILE = WORK_DIR_PATH / HOSTS_TEMPLATE_FILE_NAME
TEST_COLLECTIONS_DIR = WORK_DIR_PATH / "collections"
TEST_SIGNATURE_FILE = (
    TEST_COLLECTIONS_DIR
    / "ansible_collections"
    / COLLECTION_NAMESPACE
    / COLLECTION_NAME
    / "roles"
    / ROLE_NAME
    / "files"
    / INSTALLER_CERTIFICATE_FILE_NAME
)

ERROR_MESSAGES_FILE_PATH = ROLE_DIR_PATH / "vars" / "messages.yml"
INSTALLER_SIGNATURE_FILE_PATH = ROLE_DIR_PATH / "files" / INSTALLER_CERTIFICATE_FILE_NAME
