---
oneagent_default_arch: ppc
oneagent_default_install_dir: /opt/dynatrace/oneagent
oneagent_default_download_dir: "{{ ansible_env['TEMP'] | default('/tmp') }}"

oneagent_download_system: aix
oneagent_available_arch: "{{ [ oneagent_default_arch ] }}"
oneagent_download_arch:
  "{{ oneagent_installer_arch | default(oneagent_default_arch, true) }}"

oneagent_install_path: "{{ oneagent_passed_install_args
  | select('regex', 'INSTALL_PATH') | first
  | default(oneagent_default_install_dir)
  | regex_replace('INSTALL_PATH=(.*)', '\\1') }}"
oneagent_download_path:
  "{{ oneagent_download_dir | default(oneagent_default_download_dir, true) }}"
oneagent_installer_path: "{{ oneagent_download_path }}/\
  Dynatrace-OneAgent-AIX-{{ oneagent_version }}.sh"
oneagent_ctl_bin_path: "{{ oneagent_install_path }}/agent/tools/oneagentctl"

oneagent_install_cmd: sh {{ oneagent_installer_path }}
oneagent_uninstall_cmd: sh {{ oneagent_install_path }}/agent/uninstall.sh

oneagent_ca_cert_src_path: files/dt-root.cert.pem
oneagent_ca_cert_dest_path: "{{ oneagent_download_path }}/dt-root.cert.pem"
oneagent_certificate_verification_header: "Content-Type: multipart/signed;
  protocol=\"application/x-pkcs7-signature\"; micalg=\"sha-256\";
  boundary=\"--SIGNED-INSTALLER\"\n\n----SIGNED-INSTALLER\n"

oneagent_service_name: oneagent
