---
- name: Download OneAgent installer
  ansible.builtin.include_tasks: provide-installer/download.yml
  when: oneagent_local_installer|length == 0

- name: Transfer OneAgent installer
  ansible.builtin.include_tasks: provide-installer/transfer-{{ oneagent_system_family }}.yml
  when: oneagent_local_installer|length > 0

- name: Verify OneAgent installer signature
  ansible.builtin.include_tasks: provide-installer/signature-{{ oneagent_system_family }}.yml
  when: oneagent_system_is_unix and oneagent_verify_signature
