# Copyright 2024 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Build and test"
on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  set-up-ansible-versions:
    runs-on: ubuntu-latest
    outputs:
      community_package_versions: ${{ steps.set-up-ansible-community-package-versions.outputs.community_package_versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ansible core versions
        id: set-up-ansible-core-versions
        run: |
          minVersion="$(cat ansible-min-version.txt)"
          minVersionMajor="$(echo "$minVersion" | cut -d. -f1)"
          minVersionMinor="$(echo "$minVersion" | cut -d. -f2)"

          coreVersions=""
          for version in $(curl -s "https://pypi.org/pypi/ansible-core/json" | jq -r ".releases | keys[]" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | sort -V); do
            versionMajorMinor="$(echo "$version" | cut -d. -f1,2)"
            versionMajor="$(echo "$versionMajorMinor" | cut -d. -f1)"
            versionMinor="$(echo "$versionMajorMinor" | cut -d. -f2)"
            if [ "$versionMajor" -gt "$minVersionMajor" ] || { [ "$versionMajor" -eq "$minVersionMajor" ] && [ "$versionMinor" -ge "$minVersionMinor" ]; }; then
              if ! echo "$coreVersions" | grep -q "^$versionMajorMinor$"; then
                coreVersions="$coreVersions\n$versionMajorMinor"
              fi
            fi
          done

          uniqueCoreVersions=$(echo -e "$coreVersions" | grep -v "^$" | sort -u)
          echo "core_versions=$(jq -c -R -s \"split(\\n)[:-1]\" <<< \"$uniqueCoreVersions\")" >> $GITHUB_OUTPUT

      - name: Set up Ansible community package versions
        id: set-up-ansible-community-package-versions
        run: |
          coreVersions=${{ steps.set-up-ansible-core-versions.outputs.core_versions }}
          communityPackageVersions=""
          for v in $(echo "$coreVersions" | jq -r '.[]'); do
            minor=$(echo "$v" | cut -d. -f2)
            communityPackageVersion=$((minor - 7))
            communityPackageVersions="$communityPackageVersions\n$communityPackageVersion"
          done
          communityPackageVersions=$(echo -e "$communityPackageVersions" | grep -v "^$" | sort -u)
          echo "community_package_versions=$(jq -c -R -s \"split(\\n)[:-1]\" <<< \"$communityPackageVersions\")" >> $GITHUB_OUTPUT

  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible-package-version: ${{ fromJson(needs.set-up-ansible-versions.outputs.community_package_versions) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        uses: ./.github/actions/set-environment-variables
      - name: Set up environment
        uses: ./.github/actions/setup-build-environment
        with:
          ansible-package-version: ${{ matrix.ansible-package-version }}
      - name: Build the collection
        uses: ./.github/actions/build-collection
      - name: Run sanity tests
        uses: ./.github/actions/run-sanity-and-linter-tests
      - name: Run component tests
        uses: ./.github/actions/run-component-tests
