---
all:
  children:
    unix:
      children:
        linux:
          children:
            linux_other:
              hosts:
                www.otherhost1.com:
                www.otherhost2.com:
      vars:
        ansible_become: true
